version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_TELEMETRY_DISABLED=1
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge